service: shallot

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    slim: true
    dockerizePip: non-linux
    layer:
      name: sagemaker-pandas
      description: +sagemaker +pandas -numpy -scipy
      compatibleRuntimes:
        - python3.7
      licenseInfo: GPLv3
      allowedAccounts:
        - "*"
